spring:
  profiles:
    active: local
  application:
    name: spring-kotlin-api

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath*:db/data.sql

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/kotlintest
      username: user
      password: password
